services:
  - type: web
    name: youtube-mp3-downloader
    env: node
    plan: free
    buildCommand: |
      npm install
      npm install yt-dlp
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
