services:
  - type: web
    name: youtube-mp3-downloader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    disk:
      name: downloads
      mountPath: /downloads
      sizeGB: 1
